/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ADeclarationvariableidDv extends PDv
{
    private PTv _tv_;
    private TIdentif _identif_;

    public ADeclarationvariableidDv()
    {
        // Constructor
    }

    public ADeclarationvariableidDv(
        @SuppressWarnings("hiding") PTv _tv_,
        @SuppressWarnings("hiding") TIdentif _identif_)
    {
        // Constructor
        setTv(_tv_);

        setIdentif(_identif_);

    }

    @Override
    public Object clone()
    {
        return new ADeclarationvariableidDv(
            cloneNode(this._tv_),
            cloneNode(this._identif_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADeclarationvariableidDv(this);
    }

    public PTv getTv()
    {
        return this._tv_;
    }

    public void setTv(PTv node)
    {
        if(this._tv_ != null)
        {
            this._tv_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tv_ = node;
    }

    public TIdentif getIdentif()
    {
        return this._identif_;
    }

    public void setIdentif(TIdentif node)
    {
        if(this._identif_ != null)
        {
            this._identif_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identif_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tv_)
            + toString(this._identif_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tv_ == child)
        {
            this._tv_ = null;
            return;
        }

        if(this._identif_ == child)
        {
            this._identif_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tv_ == oldChild)
        {
            setTv((PTv) newChild);
            return;
        }

        if(this._identif_ == oldChild)
        {
            setIdentif((TIdentif) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
