/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ADivE4 extends PE4
{
    private PE4 _e4_;
    private TDiv _div_;
    private PE5 _e5_;

    public ADivE4()
    {
        // Constructor
    }

    public ADivE4(
        @SuppressWarnings("hiding") PE4 _e4_,
        @SuppressWarnings("hiding") TDiv _div_,
        @SuppressWarnings("hiding") PE5 _e5_)
    {
        // Constructor
        setE4(_e4_);

        setDiv(_div_);

        setE5(_e5_);

    }

    @Override
    public Object clone()
    {
        return new ADivE4(
            cloneNode(this._e4_),
            cloneNode(this._div_),
            cloneNode(this._e5_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADivE4(this);
    }

    public PE4 getE4()
    {
        return this._e4_;
    }

    public void setE4(PE4 node)
    {
        if(this._e4_ != null)
        {
            this._e4_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._e4_ = node;
    }

    public TDiv getDiv()
    {
        return this._div_;
    }

    public void setDiv(TDiv node)
    {
        if(this._div_ != null)
        {
            this._div_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._div_ = node;
    }

    public PE5 getE5()
    {
        return this._e5_;
    }

    public void setE5(PE5 node)
    {
        if(this._e5_ != null)
        {
            this._e5_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._e5_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._e4_)
            + toString(this._div_)
            + toString(this._e5_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._e4_ == child)
        {
            this._e4_ = null;
            return;
        }

        if(this._div_ == child)
        {
            this._div_ = null;
            return;
        }

        if(this._e5_ == child)
        {
            this._e5_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._e4_ == oldChild)
        {
            setE4((PE4) newChild);
            return;
        }

        if(this._div_ == oldChild)
        {
            setDiv((TDiv) newChild);
            return;
        }

        if(this._e5_ == oldChild)
        {
            setE5((PE5) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
