/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AInfE2 extends PE2
{
    private PE2 _e2_;
    private TInf _inf_;
    private PE3 _e3_;

    public AInfE2()
    {
        // Constructor
    }

    public AInfE2(
        @SuppressWarnings("hiding") PE2 _e2_,
        @SuppressWarnings("hiding") TInf _inf_,
        @SuppressWarnings("hiding") PE3 _e3_)
    {
        // Constructor
        setE2(_e2_);

        setInf(_inf_);

        setE3(_e3_);

    }

    @Override
    public Object clone()
    {
        return new AInfE2(
            cloneNode(this._e2_),
            cloneNode(this._inf_),
            cloneNode(this._e3_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInfE2(this);
    }

    public PE2 getE2()
    {
        return this._e2_;
    }

    public void setE2(PE2 node)
    {
        if(this._e2_ != null)
        {
            this._e2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._e2_ = node;
    }

    public TInf getInf()
    {
        return this._inf_;
    }

    public void setInf(TInf node)
    {
        if(this._inf_ != null)
        {
            this._inf_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._inf_ = node;
    }

    public PE3 getE3()
    {
        return this._e3_;
    }

    public void setE3(PE3 node)
    {
        if(this._e3_ != null)
        {
            this._e3_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._e3_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._e2_)
            + toString(this._inf_)
            + toString(this._e3_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._e2_ == child)
        {
            this._e2_ = null;
            return;
        }

        if(this._inf_ == child)
        {
            this._inf_ = null;
            return;
        }

        if(this._e3_ == child)
        {
            this._e3_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._e2_ == oldChild)
        {
            setE2((PE2) newChild);
            return;
        }

        if(this._inf_ == oldChild)
        {
            setInf((TInf) newChild);
            return;
        }

        if(this._e3_ == oldChild)
        {
            setE3((PE3) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
