/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AMoinsE3 extends PE3
{
    private PE3 _e3_;
    private TMoins _moins_;
    private PE4 _e4_;

    public AMoinsE3()
    {
        // Constructor
    }

    public AMoinsE3(
        @SuppressWarnings("hiding") PE3 _e3_,
        @SuppressWarnings("hiding") TMoins _moins_,
        @SuppressWarnings("hiding") PE4 _e4_)
    {
        // Constructor
        setE3(_e3_);

        setMoins(_moins_);

        setE4(_e4_);

    }

    @Override
    public Object clone()
    {
        return new AMoinsE3(
            cloneNode(this._e3_),
            cloneNode(this._moins_),
            cloneNode(this._e4_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMoinsE3(this);
    }

    public PE3 getE3()
    {
        return this._e3_;
    }

    public void setE3(PE3 node)
    {
        if(this._e3_ != null)
        {
            this._e3_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._e3_ = node;
    }

    public TMoins getMoins()
    {
        return this._moins_;
    }

    public void setMoins(TMoins node)
    {
        if(this._moins_ != null)
        {
            this._moins_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._moins_ = node;
    }

    public PE4 getE4()
    {
        return this._e4_;
    }

    public void setE4(PE4 node)
    {
        if(this._e4_ != null)
        {
            this._e4_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._e4_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._e3_)
            + toString(this._moins_)
            + toString(this._e4_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._e3_ == child)
        {
            this._e3_ = null;
            return;
        }

        if(this._moins_ == child)
        {
            this._moins_ = null;
            return;
        }

        if(this._e4_ == child)
        {
            this._e4_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._e3_ == oldChild)
        {
            setE3((PE3) newChild);
            return;
        }

        if(this._moins_ == oldChild)
        {
            setMoins((TMoins) newChild);
            return;
        }

        if(this._e4_ == oldChild)
        {
            setE4((PE4) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
