/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AMulE4 extends PE4
{
    private PE4 _e4_;
    private TMul _mul_;
    private PE5 _e5_;

    public AMulE4()
    {
        // Constructor
    }

    public AMulE4(
        @SuppressWarnings("hiding") PE4 _e4_,
        @SuppressWarnings("hiding") TMul _mul_,
        @SuppressWarnings("hiding") PE5 _e5_)
    {
        // Constructor
        setE4(_e4_);

        setMul(_mul_);

        setE5(_e5_);

    }

    @Override
    public Object clone()
    {
        return new AMulE4(
            cloneNode(this._e4_),
            cloneNode(this._mul_),
            cloneNode(this._e5_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMulE4(this);
    }

    public PE4 getE4()
    {
        return this._e4_;
    }

    public void setE4(PE4 node)
    {
        if(this._e4_ != null)
        {
            this._e4_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._e4_ = node;
    }

    public TMul getMul()
    {
        return this._mul_;
    }

    public void setMul(TMul node)
    {
        if(this._mul_ != null)
        {
            this._mul_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._mul_ = node;
    }

    public PE5 getE5()
    {
        return this._e5_;
    }

    public void setE5(PE5 node)
    {
        if(this._e5_ != null)
        {
            this._e5_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._e5_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._e4_)
            + toString(this._mul_)
            + toString(this._e5_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._e4_ == child)
        {
            this._e4_ = null;
            return;
        }

        if(this._mul_ == child)
        {
            this._mul_ = null;
            return;
        }

        if(this._e5_ == child)
        {
            this._e5_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._e4_ == oldChild)
        {
            setE4((PE4) newChild);
            return;
        }

        if(this._mul_ == oldChild)
        {
            setMul((TMul) newChild);
            return;
        }

        if(this._e5_ == oldChild)
        {
            setE5((PE5) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
