/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class APasouExp extends PExp
{
    private PE1 _e1_;

    public APasouExp()
    {
        // Constructor
    }

    public APasouExp(
        @SuppressWarnings("hiding") PE1 _e1_)
    {
        // Constructor
        setE1(_e1_);

    }

    @Override
    public Object clone()
    {
        return new APasouExp(
            cloneNode(this._e1_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPasouExp(this);
    }

    public PE1 getE1()
    {
        return this._e1_;
    }

    public void setE1(PE1 node)
    {
        if(this._e1_ != null)
        {
            this._e1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._e1_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._e1_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._e1_ == child)
        {
            this._e1_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._e1_ == oldChild)
        {
            setE1((PE1) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
