/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ATypeoptionelTo extends PTo
{
    private PTv _tv_;

    public ATypeoptionelTo()
    {
        // Constructor
    }

    public ATypeoptionelTo(
        @SuppressWarnings("hiding") PTv _tv_)
    {
        // Constructor
        setTv(_tv_);

    }

    @Override
    public Object clone()
    {
        return new ATypeoptionelTo(
            cloneNode(this._tv_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATypeoptionelTo(this);
    }

    public PTv getTv()
    {
        return this._tv_;
    }

    public void setTv(PTv node)
    {
        if(this._tv_ != null)
        {
            this._tv_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tv_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tv_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tv_ == child)
        {
            this._tv_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tv_ == oldChild)
        {
            setTv((PTv) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
